= Kevin Leonardo Anantha - Project Portfolio
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:imagesDir: ../images
:stylesDir: ../stylesheets

== Project: K.N.S. AddressBook
K.N.S. AddressBook is a Java desktop address book application created by *Team W11-B3* during the course of *CS2103T
Software Engineering* in AY2017/8 Semester 1. This Portfolio details my major contributions to the project, and lists our other minor contributions as well.

*Code Contributed*:
 [https://github.com/CS2103AUG2017-W11-B3/main/blob/master/collated/main/k-l-a.md[Functional Code]]
 [https://github.com/CS2103AUG2017-W11-B3/main/blob/master/collated/test/k-l-a.md[Test Code]]

=== Enhancement Added: Partial Finding

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=partialfind]

#End of Extract#

---

==== Justification

Most people will likely not fully remember their contact details, so a partial find of some kind would be very beneficial
to have in the find command. Even if they do, a partial find can still be useful in reducing the actual number of characters
someone has to type, because they can type the keywords up to a point where they're sure that it won't match most contacts
other than the one they're looking for. So, given that partial finding is more convenient for everyone, I decided that it
was more appropriate than exclusive matching.

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=partialfind]

#End of Extract#

---

=== Enhancement Added: Find by Tag


==== External behavior

---

#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=findbytag]

#End of Extract#

---

==== Justification

Similar with partial finding, there will be times where the `name` is the field that is forgotten by the user. In such
scenarios, without the ability to find by tags (or other fields), the user's capability to locate a person will be
crippled, and alongside it, the usefulness of our application. So, I decided that a find by tag was necessary. The tag
prefix is used to indicate searching by tag as the user would be most familiar with it already, given that other
commands, such as `add` and `edit`, already uses such a format.



==== Implementation

---
#Start of Extract [from: Developer Guide]# *written by Nadhira Salsabila*

include::../DeveloperGuide.adoc[tag=findbyallfield]

#End of Extract#

---

=== Enhancement Added : Sorting

==== External Behavior

---
===== Find Auto-sort


#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=n]
#End of Extract#



===== Sort Command

#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=sort]
#End of Extract#

---

==== Justification

With the target audience in mind, I thought it was likely that there would sometimes be a scenario where the user wants
to view a relatively large `find` result. Given so, I decided to implement 2 kinds of sorting, one integrated into the `find`
command, and the other as a `sort` command, in order to maximize the ease at which the user can parse through the result
list. The Auto-Sort integrated into the `find` command will help users who wants to search for a person, but only remember a short
part of their name. The `sort` command will help users who want to organize their search results, in order to record them
for other purposes.

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=sort]
#End of Extract#

---
=== Enhancement Added : Import & Export Command

==== External Behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=exim]
#End of Extract#

---
==== Justification

As the application provides automatic saving, I thought it was prudent to have a manual saving mechanism, in order for
users to defend against accidents that the `undo`/`redo` mechanism can't fix, such as accidentally closing the application
without realizing a mistaken delete. It also provides a way for less savvy users who does not know how to manually back
up and import their data to do so. +
Keeping that in mind, the current behavior mainly supports backing up your data and
loading them afterwards, instead of being able to switch your address book to work on another one, since that is not the
intended purpose.


==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=importexport]
#End of Extract#

---
=== Enhancement Proposed: Boolean Searching

==== Justification

Given the target audience of our product, it is plausible that they would need to find people who matches certain
criteria without having a specific person in mind. For example, they might need to find everyone who are clients but not
currently overseas. In current form, there is no way for them to do this easily. +
Boolean searching will allow them to search using AND and NOT keywords to enable a much easier searching experience.

=== Other Contributions

* *Modified `add` to accept missing prefixes other than name*
** Each missing prefix will be shown with a default value to indicate their absence
** Pull Request : https://github.com/CS2103AUG2017-W11-B3/main/pull/39[#39]

* *Set up various project tools, such as :*
** Appveyor and Coveralls configuration for github repo.
** Github-pages website, via Travis CI.

* *Created the table for command cheat sheet in the user guide*
** Pull Request : https://github.com/CS2103AUG2017-W11-B3/main/pull/63[#63]
